Remove s3
horizoncd/horizon pull request #108
Opened 2023-03-27 08:19 UTC by xuzhu-591

2023-03-27 11:38 UTC, kilosonc requested changes

2023-03-27 11:38 UTC, kilosonc commented on pkg/cluster/tekton/collector/collector_no_storage.go
> +	// only collect pipelineRun result and Start and end time
what's the meaning?

2023-03-27 11:38 UTC, kilosonc commented on pkg/cluster/tekton/collector/collector_no_storage.go
> +	// only collect pipelineRun result and Start and end time
start time and end time?

2023-03-27 11:38 UTC, kilosonc commented on pkg/cluster/tekton/collector/collector_no_storage.go
> +func NewNoStorageCollector(tekton tekton.Interface) *NoStorageCollector {
*NoStorageCollector => Interface?

2023-03-27 11:38 UTC, kilosonc commented on pkg/cluster/tekton/collector/collector_s3.go
> +	logCh, errCh, err := c.tekton.GetPipelineRunLogByID(ctx, pr.CIEventID)
this logic is not that right, collector should not access k8s directly

2023-03-27 11:38 UTC, kilosonc commented on config.yaml
> +      enabled: false
prefering
buildlogstroge:
  type: s3 or dummy
  accessKey: ""
  secretKey: ""

2023-03-28 02:04 UTC, iamyeka commented on config.yaml
> +    logStorage:
Add some comments? Please point out what kinds of value could be taken here and what's the use case of each.

2023-03-28 02:18 UTC, iamyeka commented on pkg/cluster/tekton/collector/collector.go
> +type Log struct {
Why use a struct like this?

2023-03-28 02:28 UTC, iamyeka commented on pkg/cluster/tekton/collector/collector.go
> +type Log struct {
Looks like another Log has been defined in core/controller/pipelinerun/controller.go

2023-03-28 03:12 UTC, kilosonc approved these changes

2023-03-28 12:27 UTC, iamyeka commented on config.yaml
> +      #   dummy: a dummy log storage, build logs are not stored and get them directly from k8s
#   s3: Minio is used by default, and you can also specify your own s3 storage.
      #   dummy: A dummy log storage. Building logs are not stored and Horizon gets them directly from k8s.

2023-03-29 07:33 UTC, merged