add query applications in one group
horizoncd/horizon pull request #60
Opened 2023-03-03 03:30 UTC by work-jlsun

2023-03-03 03:58 UTC, xuzhu-591 commented on core/http/api/v2/application/apis.go
> +			response.AbortWithRPCError(c, rpcerror.ParamError.WithErrMsg("user id is not a number"))
user => group

2023-03-03 03:58 UTC, xuzhu-591 commented on pkg/application/dao/dao.go
> +	List(ctx context.Context, userAuthorizedGroupIDs []uint, query *q.Query) (int, []*models.Application, error)
Could you add ut for manager.List ?

2023-03-03 04:01 UTC, xuzhu-591 commented
lint failed

2023-03-03 06:09 UTC, kilosonc requested changes
Please take comments below into consideration

2023-03-03 06:09 UTC, kilosonc commented on core/http/api/v2/application/apis.go
> +	idStr = c.Query(common.ApplicationQueryByGroup)
Using array to support multiple groups?

2023-03-03 06:09 UTC, kilosonc commented on pkg/application/dao/dao.go
> +				statement = statement.Where("a.group_id = ?", v)
a.group_id in ?

2023-03-03 11:00 UTC, work-jlsun commented on pkg/application/dao/dao.go
> +				statement = statement.Where("a.group_id = ?", v)
currently just  support group =

2023-03-03 11:00 UTC, work-jlsun commented on core/http/api/v2/application/apis.go
> +	idStr = c.Query(common.ApplicationQueryByGroup)
currently not support

2023-03-06 09:57 UTC, kilosonc approved these changes

2023-03-06 10:16 UTC, xuzhu-591 approved these changes

2023-03-06 10:18 UTC, merged